# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN dnf --enablerepo=powertools install -y \
      java-17-openjdk-devel \
      maven \
      ca-certificates \
 && dnf clean all \
 && ln -sfn "$(dirname $(dirname $(readlink -f $(which javac))))" /usr/lib/jvm/cudf-smoke-jdk

ENV JAVA_HOME=/usr/lib/jvm/cudf-smoke-jdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"
